name: business_card_admin
description: Business Card Admin
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  go_router: ^10.0.0
  retrofit: ^4.0.1
  dio: ^5.3.0
  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.8
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  json_serializable:
  retrofit_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#151928"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/logo.png"
    remove_alpha_ios: true