name: business_card_admin
description: Business Card Admin
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  go_router: ^10.0.0
  retrofit: ^4.0.1
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.8
  path_provider: ^2.0.15
  image_picker: ^1.0.2
  flutter_dotenv: ^5.1.0
  flutter_nfc_kit: ^3.3.1
  ndef: ^0.3.1
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.2
  flutter_colorpicker: ^1.0.3
  font_awesome_flutter: ^10.5.0
  textfield_tags: ^2.0.2

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  json_serializable:
  retrofit_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - production.env

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#151928"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/logo.png"
    remove_alpha_ios: true